name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v3
    - name: NPM install
      run: |
        npm install
    - name: Test
      run: |
        npm run pretest
        npm run test
    - name: Test packaging
      run: |
        npx vsce package
